exchange: binance
symbol: BTCUSDT
amount: 0.001
api_key: ""
api_secret: ""
db_path: trading_bot.db
smtp_server: smtp.example.com
smtp_port: 465
sender_email: votre_email@example.com
email_password: ""
receiver_email: destinataire@example.com
interval: 1m
